=== mrrishit909/decision-universe/data/contracts/m02_sampling.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "additionalProperties": false,
 "properties": {
  "first_1000_u32": {
   "items": {
    "type": "integer"
   },
   "maxItems": 1000,
   "minItems": 1000,
   "type": "array"
  },
  "generated_at": {
   "type": "string"
  },
  "moments": {
   "type": "object"
  },
  "normal_first": {
   "items": {
    "type": "number"
   },
   "type": "array"
  },
  "schema_version": {
   "const": "v1"
  },
  "seed": {
   "type": "integer"
  },
  "seed_vectors": {
   "items": {
    "additionalProperties": false,
    "properties": {
     "first_16_u32": {
      "items": {
       "type": "integer"
      },
      "maxItems": 16,
      "minItems": 16,
      "type": "array"
     },
     "seed": {
      "type": "integer"
     }
    },
    "required": [
     "seed",
     "first_16_u32"
    ],
    "type": "object"
   },
   "minItems": 3,
   "type": "array"
  },
  "spec": {
   "type": "object"
  },
  "tags": {
   "additionalProperties": {
    "pattern": "^(OBSERVED|DERIVED|PREDICTED|SIMULATED|SYNTHETIC)(/(OBSERVED|DERIVED|PREDICTED|SIMULATED|SYNTHETIC))*$",
    "type": "string"
   },
   "minProperties": 1,
   "type": "object"
  },
  "tolerance": {
   "additionalProperties": false,
   "properties": {
    "abs": {
     "type": "number"
    },
    "note": {
     "type": "string"
    },
    "rel": {
     "type": "number"
    }
   },
   "required": [
    "abs",
    "rel",
    "note"
   ],
   "type": "object"
  },
  "uniform_first": {
   "items": {
    "type": "number"
   },
   "type": "array"
  }
 },
 "required": [
  "schema_version",
  "generated_at",
  "tags",
  "spec",
  "seed",
  "first_1000_u32",
  "uniform_first",
  "normal_first",
  "seed_vectors",
  "tolerance",
  "moments"
 ],
 "title": "Sampling",
 "type": "object"
}

=== mrrishit909/decision-universe/site/public/data/m02_sampling.json
{"first_1000_u32":[3595447901,1865114723,2071441898,2576159172,126340258,2954739012,2461620194,2498548250,1700629364,1980421523,3122835788,1353663668,3883150812,515397485,1545580602,3061031487,2747067301,293332030,1105099066,38536629,3851897228,663325639,374309837,2619312530,2299933643,4176882950,3619738408,1457495459,3035814983,2212306998,3963764123,666256589,2371274041,1206850216,1152103607,1544313252,3352234469,2359839994,2835682870,2746219033,312436038,3989565305,14895627,2438607158,1857404575,2196466431,2047436998,1970959651,3890569091,3562280168,2356292550,1370700897,2376102255,1851281887,4160711847,1131749756,3800276060,2544493286,1384643867,1429632371,3207878655,2425222045,900299111,3965540245,1846983975,3388025791,2419106878,2395700807,4206078677,3055397912,909666430,229602026,4125585055,3175213186,1364004453,3224573092,1863177410,849200115,766457469,2235790177,1843400474,3433617666,1248587126,4162386927,46931981,2367583937,2987183174,2261022753,2849954702,1586767731,4075939821,3143102723,606366352,3333632240,2478057934,3192714860,1259980163,655830253,2598059725,3915841057,3972384500,3458207761,1952527687,51796344,1836542740,4209145595,1799150463,2400678157,2753826483,2268016931,3412320468,286119088,1962783697,2979179199,1061910351,2387190709,3281135994,539990288,326817661,3470877057,1711535948,1691796666,2835361862,809604216,3049594482,983880073,2746137889,899796522,4289239569,486721823,2977724553,2295987857,3604436653,1326422979,3644541347,2797555690,2949730562,3529468883,3616807495,3338836260,975183907,1464198024,248451930,488814964,4001351339,1175908281,966434494,1379014763,2023248726,3396879083,872422262,4199157060,3870705151,4260920834,3789643573,2053989131,833957659,3509258696,3805099109,4043286013,2583955638,1773347600,210007391,810390110,3246799982,2542755477,2873914157,1269919782,1382338548,2786868499,3529734834,1675276423,582695068,2135555094,2122327023,3633485275,411498669,479672453,2188060946,1606750056,3764829892,3066016039,3579123498,1984696706,520186821,981566462,2199074352,3255956102,2925864695,2488302369,537990531,1582012820,1388305657,1382552457,3288359917,3558212846,574931520,1067268337,1914883764,3767627859,3131330591,1169156790,629855507,560059371,1086099495,1493717822,217715643,3388275866,637671219,4246245904,1448353404,3180753643,3983580832,233369774,676085444,1375458377,2810381355,3056249737,864572713,4286004068,3084443499,1970971770,1570036872,3627605444,3848064061,3046597900,250150396,2719764237,1486504629,2209432214,423727409,1775006706,3936457818,1547841928,931780234,2644085082,289309779,2965595319,1651018760,3286510092,2357892391,1231332872,2887293593,1211674371,3583099652,638763363,695308721,3802095193,1287234105,2551834071,4070130138,91513509,3504742500,3228127406,2305319345,3046734402,1043772256,3858287294,1740566966,2680376103,2383373140,1393410461,1812214977,1703308339,2245800380,3396446799,470281525,2079795508,3762359485,3023870766,3806045370,814897364,3822022047,1571881979,162806080,4255224344,3451204152,1506608727,3404261918,1624434296,1578369256,2729865084,2413451040,793194922,2558188325,3350724301,1235383648,345707114,3645575703,2851182594,725302356,874130251,1603917126,3018042803,3827940057,3509957162,395313270,3482885773,2557816026,2405695785,866634173,3158171168,1484107724,1801844062,1419370901,2405244040,1995898363,3970596720,335176781,3450944704,2186842591,3970131613,3283788131,3716131335,4048878551,276564405,2715266509,3918745059,3737029613,1340249979,2498657571,1944498208,4057146471,2746763836,3450924610,1502272896,2142077465,1882064940,2010140013,4213551857,3518259547,826758851,1515812922,1126872960,4290492665,2295529375,1512389794,559709299,2286029553,2230825793,4013684056,4061917967,2227736661,1725010194,3471152457,3268751622,3310803765,3090750970,2902266749,1550080144,3643455135,4120708011,2572260088,14983412,3800852531,552583604,3463982261,3085998206,442946659,3463355054,1107599583,2371294117,3541563662,1973464880,837363250,3990557924,3515509871,1931909309,3443439357,2582694056,2941336085,375011054,461657568,2029906122,2452218773,2929413770,4115130013,3664404852,3993057665,1451175386,610294476,3202275172,1962701355,1847954983,3749662062,1998055754,338331798,3690290684,205775076,1776701595,1317669129,2506006000,618888085,3564510530,179935484,1213891066,1134633253,2546397207,2208536713,2201293117,2943979981,1196641301,3131124343,877678937,2085501795,976043982,136947918,3937019917,1151261403,1949940094,2691412765,3046984314,1312928565,2386844481,3674007636,3276139075,2765726523,2265556569,2782658516,267888334,3373179818,946316238,3139522709,505287792,4129000701,3219690381,2839633656,4016159344,278924427,219288090,1696352495,391528976,4133688553,2663608767,3782757796,3360649159,2914289153,92184861,3461310161,2119785957,3038708437,394383556,2204129767,1635879563,1939701924,2802368501,3704120944,636362981,2932756987,895489350,4238646619,1394837748,2477563987,2793097647,2720984961,1103216007,2774443607,3056298246,132512571,3435966035,2758948692,1736042499,3968486728,738273953,2787454446,355864615,1766378548,4267909974,407188790,1576105162,310878597,2303606451,2033108893,2862845927,1534007813,3697392469,3802667130,1490537618,3381935625,39159176,3132980623,1391728996,2804265512,1689184945,232463369,1673500405,193391168,1985557445,3816501917,4189563537,569306325,3872681431,2875759167,3859165467,3035879205,3707186395,3685351157,2750655632,2092807639,3948933761,345021566,1939752938,4129916297,480648889,2822977508,260386096,1677322487,2235441682,1936482513,4137670919,214036812,874941524,851322262,779978399,3752669139,785861629,3070092547,3289209886,919678596,1563845324,3526884703,2300251851,4130789892,3949614182,1355891293,342515729,86823725,304028161,714656427,4151490934,4132613274,4073224810,1007565451,1614612320,1567093590,2387598361,1075045543,1468621469,1685153153,1909840558,2685176031,1785339970,3423486615,584774284,1878886523,3036099444,2092630897,2765475870,2703772890,3356650519,838057416,3129173152,3339734970,2610036004,2958636401,681694831,2408885337,83221359,59936099,2304955642,1824933115,3201974067,566371118,1358356419,1209213172,7880332,2051191386,2146105614,1935666181,3497733679,3464573095,3856397697,4200892010,2585704405,2977212783,2171897285,1346090135,3556319052,4063930711,2062492439,1042542036,3726037808,1489672820,152256626,23266776,3868948882,1092856669,2649728200,46444643,4152614031,654857320,2095407261,475044744,3086610856,1501408663,3496271620,1337812308,4020893608,1374626444,812696730,2596722372,224293668,1250612235,1385666058,3840374272,920313624,1020763447,1187768633,1280770277,2273105729,3638444025,577155423,2399501211,2367215212,3387901730,1676337299,1097438499,2932511324,2454935511,3157474032,2784127124,2725338212,4278444028,3692509194,817039925,1707683483,3209624614,1876777341,440659993,697865684,831905941,662261785,2454869172,3756915346,397762008,1802633743,2711473958,4049851461,1677666392,461156762,1461323646,471391028,798117097,1852864793,2972800173,3531234537,1032267542,1782976654,499988368,3628945843,3414257476,1012506999,2939566246,532692675,89518342,2589243716,1203041656,2643943961,846067503,93243284,2799044400,4276764492,2606777935,1806870170,4868828,478083512,1876533150,3754355152,2111430313,2254343797,3357490399,1349718462,2930724829,4149738976,1882146412,2758430384,2963203341,3824341003,2886392166,3464681387,4212747862,2453143602,332736588,2782938455,3322012438,3242555012,1074567514,2280847949,916724627,2500750036,575673544,1569231975,618995202,2538542632,3269351699,3243016301,1067853694,1702921021,2505623496,260827105,241647854,3219320968,4283477448,2399922080,3810936809,289102595,3119211160,3198200684,2246075930,903243705,710989891,4077055755,4241525298,1106692645,528078526,1886550392,1959279189,649104935,288187284,2622455003,846573152,1526446816,3582176109,1616072040,712407989,1746180803,1495293730,1309943020,1049573781,218203240,1449825842,3152325200,4100885034,1739098696,74939294,2637321665,1115144002,1769257117,856922942,2469921166,3367491666,3869007836,2051946346,2931271476,530918870,3838559250,2803708698,1610143284,3915153177,995563185,1865830840,3709563608,885689590,3805725101,3494040952,1993224213,2686054282,2367905990,1571439175,110458046,3146427195,1602664209,185010513,4173013160,3040723928,1390550295,1637550873,2011692255,3745643482,2464421801,2271620342,670968437,2726414797,507202996,1043138194,4182575636,1983793040,7303433,2574553654,1435391163,544360899,3623519660,1194069160,579455589,2998539497,2469787896,206535036,4191641268,2587113549,3881834847,1835901022,1954038971,1795908964,2596824293,356142565,510182732,2172516545,3491270462,3938734763,3285978248,2029906393,2101596296,2140940094,2419037793,3133074094,767379097,1690425353,1636913020,1368411657,177203475,579170317,1232568562,3132559486,3949480059,1708344654,3894786500,3421676116,1649480374,1615114930,1743082805,3590368691,240272711,1912037597,835728873,3019813596,24768730,3896313606,3573378034,1354001821,1555774934,1602250287,1383211097,4232575311,1387235255,1047388937,2513980578,2388111200,1724165427,1319343898,1110289592,1381722760,2619467829,1484204560,176801202,2692189649,3795334709,532682298,1591464817,3932875616,131348550,521568458,815510160,357050250,3488177456,4159218845,1873151496,2880342492,2353183488,3166570962,1926088507,3066818287,1672119440,1801838838,2726738872,1965418500,3553501581,2782749040,1357077537,2545021477,1002952007,2249417296,189456281,924013416,1461609476,3290754370,3667295985,611208873,3605062847,2913891434,2585802553,3595862579,1472844107,2675435178,738817102,3563950151,740708990,2720252222,3527613656,3456255407,344111775,3557726773,2399838426,2352069882,2325873743,2231856808,3943888562,3959020051,1048060048,1686574996,3837786168,2319141645,1816632676,1479202387,2006501140,1731691295,497803411,1524606342,1760965376,1323573595,1654694109,2501617898,3901495258,2731030476,3752137648,1457080501,1586696421,1113104983,1688215198,1231874897,1655531045,106460687,3757207532,3168914241,3467081388,310532949,1136804283,963869998,1106
